#!/bin/sh
#
#     SUSE system statup script for eureka-center
#     Copyright (C) 2007  Pascal Bleser
#
#     This library is free software; you can redistribute it and/or modify it
#     under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation; either version 2.1 of the License, or (at
#     your option) any later version.
#
#     This library is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     Lesser General Public License for more details.
#
#     You should have received a copy of the GNU Lesser General Public
#     License along with this library; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
#     USA.
#
### BEGIN INIT INFO
# Provides:          eureka-center
# Required-Start:    $local_fs $remote_fs $network $time $named
# Should-Start: $time sendmail
# Required-Stop:     $local_fs $remote_fs $network $time $named
# Should-Stop: $time sendmail
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: eureka-center Automation Server
# Description:       eureka-center Automation Server
### END INIT INFO

export CLASS_PATH=""


# Check for existence of needed config file and read it
EUREKA_SERVER_CONFIG=/disk1/webserver/eureka-center/eureka-center.cfg
test -e "$EUREKA_SERVER_CONFIG" || { echo "$EUREKA_SERVER_CONFIG not existing";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }
test -r "$EUREKA_SERVER_CONFIG" || { echo "$EUREKA_SERVER_CONFIG not readable. Perhaps you forgot 'sudo'?";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }

EUREKA_SERVER_PID_FILE="/var/run/eureka-center.pid"

# Source function library.
. /etc/init.d/functions

# Read config
[ -f "$EUREKA_SERVER_CONFIG" ] && . "$EUREKA_SERVER_CONFIG"


# Set up environment accordingly to the configuration settings
[ -n "$EUREKA_SERVER_HOME" ] || { echo "EUREKA_SERVER_HOME not configured in $EUREKA_SERVER_CONFIG";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }
[ -d "$EUREKA_SERVER_HOME" ] || { echo "EUREKA_SERVER_HOME directory does not exist: $EUREKA_SERVER_HOME";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 1; fi; }


test -r "$EUREKA_SERVER_JAR" || { echo "$EUREKA_SERVER_JAR not installed";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 5; fi; }

# Search usable Java as /usr/bin/java might not point to minimal version required by eureka-center.
# see http://www.nabble.com/guinea-pigs-wanted-----Hudson-RPM-for-RedHat-Linux-td25673707.html

candidates="
/usr/bin/java
/etc/alternatives/java
/usr/lib/jvm/java-1.8.0/bin/java
/usr/lib/jvm/jre-1.8.0/bin/java
/usr/lib/jvm/java-1.7.0/bin/java
/usr/lib/jvm/jre-1.7.0/bin/java
/usr/bin/java
"
for candidate in $candidates
do
  [ -x "$EUREKA_SERVER_JAVA_CMD" ] && break
  EUREKA_SERVER_JAVA_CMD="$candidate"
done


JAVA_CMD="$EUREKA_SERVER_JAVA_CMD $EUREKA_SERVER_JAVA_OPTIONS -DEUREKA_SERVER_HOME=$EUREKA_SERVER_HOME -jar $EUREKA_SERVER_JAR"
echo $JAVA_CMD
PARAMS="  "
[ -n "$EUREKA_SERVER_ARGS" ] && PARAMS="$PARAMS $EUREKA_SERVER_ARGS"


RETVAL=0

case "$1" in
    start)
	echo -n "Starting eureka-center "
	echo -n "$JAVA_CMD $PARAMS"
	daemon --user "$EUREKA_SERVER_USER" --pidfile "$EUREKA_SERVER_PID_FILE" $JAVA_CMD $PARAMS > /dev/null
	echo -n "Starting eureka-center complete "
	RETVAL=$?
	if [ $RETVAL = 0 ]; then
	    success
	    echo > "$EUREKA_SERVER_PID_FILE"  # just in case we fail to find it
            MY_SESSION_ID=`/bin/ps h -o sess -p $$`
            # get PID
            /bin/ps hww -u "$EUREKA_SERVER_USER" -o sess,ppid,pid,cmd | \
            while read sess ppid pid cmd; do
		[ "$ppid" = 1 ] || continue
		# this test doesn't work because eureka-center sets a new Session ID
                # [ "$sess" = "$MY_SESSION_ID" ] || continue
	       	echo "$cmd" | grep $EUREKA_SERVER_JAR > /dev/null
		[ $? = 0 ] || continue
		# found a PID
		echo $pid > "$EUREKA_SERVER_PID_FILE"
	    done
	else
	    failure
	fi
	echo
	;;
    stop)
	echo -n "Shutting down eureka-center "
	killproc eureka-center
	RETVAL=$?
	echo
	;;
    try-restart|condrestart)
	if test "$1" = "condrestart"; then
		echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
	fi
	$0 status
	if test $? = 0; then
		$0 restart
	else
		: # Not running is not a failure.
	fi
	;;
    restart)
	$0 stop
	$0 start
	;;
    force-reload)
	echo -n "Reload service eureka-center "
	$0 try-restart
	;;
    reload)
    	$0 restart
	;;
    status)
    	status eureka-center
	RETVAL=$?
	;;
    probe)
	## Optional: Probe for the necessity of a reload, print out the
	## argument to this init script which is required for a reload.
	## Note: probe is not (yet) part of LSB (as of 1.9)

	test "$EUREKA_SERVER_CONFIG" -nt "$EUREKA_SERVER_PID_FILE" && echo reload
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
exit $RETVAL
